version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-sdk
      - if [ -d "src/auth" ]; then cd src/auth && npm install && cd ../..; fi
      - if [ -d "src/orders" ]; then cd src/orders && npm install && cd ../..; fi
      - if [ -d "src/products" ]; then cd src/products && npm install && cd ../..; fi

  pre_build:
    commands:
      - mkdir -p dist/$ENV

  build:
    commands:
      - if [ ! -d "src/auth" ]; then echo "ERROR: src/auth missing" && exit 1; fi
      - (cd src/auth && zip -r ../../dist/$ENV/auth.zip .) || exit 1
      - (cd src/orders && zip -r ../../dist/$ENV/orders.zip .) || exit 1
      - (cd src/products && zip -r ../../dist/$ENV/products.zip .) || exit 1

  post_build:
    commands:
      - aws s3 sync dist/$ENV/ s3://$LAMBDA_DEPLOYMENT_BUCKET/backend/$ENV/
      - if [ ! -f "templates/backend.yml" ]; then echo "Missing template" && exit 1; fi
      - aws cloudformation package --template-file templates/backend.yml --s3-bucket $LAMBDA_DEPLOYMENT_BUCKET --output-template-file packaged-template.yml
      - aws s3 cp packaged-template.yml s3://$LAMBDA_DEPLOYMENT_BUCKET/templates/

artifacts:
  files:
    - packaged-template.yml
  discard-paths: yes