version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing AWS SDK..."
      - npm install -g aws-sdk
      - echo "Installing Lambda dependencies..."
      - for dir in src/auth src/orders src/products; do
          if [ -d "$dir" ]; then
            echo "Installing in $dir"
            (cd "$dir" && npm install)
          else
            echo "Warning: $dir not found"
          fi
        done

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "ENV $ENV"
      - echo "LAMBDA_DEPLOYMENT_BUCKET $LAMBDA_DEPLOYMENT_BUCKET"
      - echo "Creating directories..."
      - mkdir -p dist/$ENV output_templates
      - echo "Current structure:"
      - ls -la
      - echo "Template verification:"
      - aws cloudformation validate-template --template-body file://templates/backend.yml || exit 1

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Packaging Lambda functions..."
      - for lambda in auth orders products; do
          if [ ! -d "src/$lambda" ]; then
            echo "Error: src/$lambda missing!"
            exit 1
          fi
          echo "Packaging $lambda..."
          (cd "src/$lambda" && zip -r "../../dist/$ENV/$lambda.zip" .) || exit 1
        done

  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Uploading Lambda packages..."
      - aws s3 sync dist/$ENV/ s3://$LAMBDA_DEPLOYMENT_BUCKET/backend/$ENV/ --acl bucket-owner-full-control
      
      - echo "=== TEMPLATE PACKAGING ==="
      - echo "Cleaning previous packages..."
      - rm -f output_templates/*
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package \
          --template-file templates/backend.yml \
          --s3-bucket $LAMBDA_DEPLOYMENT_BUCKET \
          --output-template-file output_templates/backend-packaged.yml \
          --force-upload
      - echo "Validating packaged template..."
      - aws cloudformation validate-template --template-body file://output_templates/backend-packaged.yml || exit 1
      - echo "Uploading packaged template..."
      - aws s3 cp output_templates/backend-packaged.yml s3://$LAMBDA_DEPLOYMENT_BUCKET/templates/ --acl bucket-owner-full-control
      - echo "Verifying upload..."
      - aws s3 ls s3://$LAMBDA_DEPLOYMENT_BUCKET/templates/backend-packaged.yml || exit 1

artifacts:
  files:
    - output_templates/backend-packaged.yml
    - templates/backend.yml
    - dist/$ENV/*
  base-directory: .